<?php

// Load Nette Framework or autoloader generated by Composer
use Nette\Configurator;



require __DIR__ . '/../libs/composer/autoload.php';

\Nette\Diagnostics\Debugger::$maxDepth = 6;

$configurator = new Configurator;

// Enable Nette Debugger for error visualisation & logging
//$configurator->setDebugMode(TRUE);
//$configurator->setDebugMode(FALSE);
$configurator->enableDebugger(__DIR__ . '/../log');

// Specify folder for cache
$configurator->setTempDirectory(__DIR__ . '/../temp');

// Enable RobotLoader - this will load all classes automatically
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->addDirectory(__DIR__ . '/../libs')
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$container = $configurator->createContainer();

function getNextrasDemosSource($path)
{
	$file = __DIR__ . '/../libs/composer/nextras/' . $path;
	if (!file_exists($file)) {
		throw new \Nette\FileNotFoundException("File '$file' not found.");
	}
	return $file;
}

function getNextrasDemosSourceWeb($path)
{
	$file = __DIR__ . '/../libs/composer/nextras/' . $path;
	if (!file_exists($file)) {
		throw new \Nette\FileNotFoundException("File '$file' not found.");
	}
	return '/../libs/composer/nextras/' . $path;
}


return $container;
