<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'WebLoader' => array($vendorDir . '/janmarek/webloader'),
    'Nextras\\Latte\\Macros' => array($vendorDir . '/nextras/latte-macros'),
    'Nextras\\Forms' => array($vendorDir . '/nextras/forms'),
    'Nextras\\Datagrid' => array($vendorDir . '/nextras/datagrid'),
    'LeanMapper' => array($vendorDir . '/tharos/leanmapper'),
    'Kdyby\\Replicator\\' => array($vendorDir . '/kdyby/forms-replicator/src'),
);
